### ISSUE TITLE
Implement food

### ISSUE THREAD

**Issue by KamilC00** [KamilC00/SnakeGame#4]
https://github.com/KamilC00/SnakeGame/blob/8c52da7407fa4f82ddd3225339e904473ea11a9b/SnakeGame/Program.cs#L13-L20

**Comment by Biggy1606** [comment]
Uncommenting code could be useful 
![ClipWindowsGIF](https://github.com/KamilC00/SnakeGame/assets/19650084/36e9d6f0-240e-494c-a15e-f698e98cfdbc)
